// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./users_mock.go -package users -source $GOFILE

package users

import (
	"context"

	"blog/rpc/user/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	RespGetAll = user.RespGetAll
	ReqUser    = user.ReqUser
	User       = user.User
	CommResp   = user.CommResp
	LoginReq   = user.LoginReq
	RespLogin  = user.RespLogin
	ReqUserId  = user.ReqUserId
	ReqGetAll  = user.ReqGetAll

	Users interface {
		Login(ctx context.Context, in *ReqUser) (*RespLogin, error)
		Create(ctx context.Context, in *ReqUser) (*CommResp, error)
		Update(ctx context.Context, in *User) (*CommResp, error)
		Delete(ctx context.Context, in *ReqUserId) (*CommResp, error)
		Get(ctx context.Context, in *ReqUserId) (*User, error)
		GetAll(ctx context.Context, in *ReqGetAll) (*RespGetAll, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) Login(ctx context.Context, in *ReqUser) (*RespLogin, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUsers) Create(ctx context.Context, in *ReqUser) (*CommResp, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.Create(ctx, in)
}

func (m *defaultUsers) Update(ctx context.Context, in *User) (*CommResp, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.Update(ctx, in)
}

func (m *defaultUsers) Delete(ctx context.Context, in *ReqUserId) (*CommResp, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.Delete(ctx, in)
}

func (m *defaultUsers) Get(ctx context.Context, in *ReqUserId) (*User, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.Get(ctx, in)
}

func (m *defaultUsers) GetAll(ctx context.Context, in *ReqGetAll) (*RespGetAll, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.GetAll(ctx, in)
}
